package com.omnistrike.framework;

import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.http.message.responses.HttpResponse;

import java.util.Set;
import java.util.regex.Pattern;

/**
 * Framework-level guard against WAF blocks, rate limits, and server errors
 * that would cause false positives if analyzed by scanner modules.
 *
 * Every active scanner module should call {@link #isUsableResponse(HttpRequestResponse)}
 * or {@link #isUsableResponse(HttpResponse)} BEFORE analyzing a response body for
 * vulnerability patterns. If this returns false, the module should skip the response
 * entirely — it came from a WAF/rate-limiter/load-balancer, not the application.
 *
 * Zero-FP rule: a response from a WAF block page can contain ANY keywords
 * (SQL error messages, stack traces, template syntax, etc.) because the WAF
 * itself is a web application. Analyzing these for vulnerability patterns
 * produces false positives.
 */
public final class ResponseGuard {

    private ResponseGuard() {}

    /** ThrottleController callback — notified when a WAF block is detected. */
    private static volatile ThrottleController throttleController;

    /** Set the ThrottleController so auto-throttle can react to WAF blocks. */
    public static void setThrottleController(ThrottleController controller) {
        throttleController = controller;
    }

    // ── Status codes that indicate the response is NOT from the application ──

    /** HTTP 429 Too Many Requests — rate limiter kicked in. */
    private static final int RATE_LIMITED = 429;

    /** HTTP 503 Service Unavailable — often returned by WAF/CDN during blocking or maintenance. */
    private static final int SERVICE_UNAVAILABLE = 503;

    /** HTTP 406 Not Acceptable — WAF rejecting payload content type. */
    private static final int NOT_ACCEPTABLE = 406;

    /** HTTP 413 Payload Too Large — server rejecting request size, not processing it. */
    private static final int PAYLOAD_TOO_LARGE = 413;

    /** HTTP 502 Bad Gateway — reverse proxy/CDN error, response is from the proxy. */
    private static final int BAD_GATEWAY = 502;

    /** HTTP 504 Gateway Timeout — reverse proxy timeout, not the application. */
    private static final int GATEWAY_TIMEOUT = 504;

    /** HTTP 520-530 — Cloudflare/CDN-specific error codes. */
    private static final int CLOUDFLARE_RANGE_START = 520;
    private static final int CLOUDFLARE_RANGE_END = 530;

    /** Status codes that are ALWAYS from infrastructure, never from the application. */
    private static final Set<Integer> INFRASTRUCTURE_STATUS_CODES = Set.of(
            RATE_LIMITED, SERVICE_UNAVAILABLE, NOT_ACCEPTABLE,
            PAYLOAD_TOO_LARGE, BAD_GATEWAY, GATEWAY_TIMEOUT
    );

    // ── WAF block page body patterns ────────────────────────────────────────
    // These indicate the response body was generated by a WAF, not the application.
    // Only checked on 403 responses (since applications also use 403 legitimately).

    private static final Pattern WAF_BODY_PATTERN = Pattern.compile(
            "(?i)"
                    // Cloudflare signatures
                    + "access denied.*cloudflare"
                    + "|attention required.*cloudflare"
                    + "|cloudflare ray id"
                    + "|cf-ray"
                    + "|checking your browser before accessing"   // Cloudflare JS challenge on 200
                    + "|enable javascript and cookies to continue" // Cloudflare challenge page
                    + "|cf-chl-bypass"                              // Cloudflare challenge bypass token
                    + "|challenges\\.cloudflare\\.com"              // Cloudflare challenge script URL
                    // Generic WAF signatures
                    + "|blocked by.*(?:mod_security|modsecurity|imperva|incapsula|sucuri|akamai|f5|barracuda|fortinet|citrix|aws waf|azure)"
                    + "|web application firewall"
                    + "|request blocked"
                    + "|your request has been blocked"
                    + "|this request was blocked"
                    + "|the requested url was rejected"
                    + "|suspicious activity"
                    + "|automated request"
                    + "|rate limit(?:ed|ing)"
                    + "|too many requests"
                    + "|please retry after"
                    + "|<title>\\s*403 forbidden\\s*</title>"
                    + "|<title>\\s*error\\s*</title>.*(?:cloudflare|akamai|incapsula)"
                    // Imperva/Incapsula
                    + "|incapsula incident id"
                    + "|powered by incapsula"
                    // Sucuri
                    + "|sucuri website firewall"
                    + "|access denied.*sucuri"
                    // AWS WAF
                    + "|<title>\\s*request blocked\\s*</title>"
                    + "|aws waf"
    );

    // ════════════════════════════════════════════════════════════════════════
    //  Public API — modules call these before analyzing responses
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Returns true if the response is usable for vulnerability analysis.
     * Returns false if the response is from a WAF, rate limiter, or infrastructure
     * component — analyzing it would produce false positives.
     *
     * Modules should call this BEFORE checking response body for vuln patterns:
     * <pre>
     *   HttpRequestResponse result = api.http().sendRequest(modified);
     *   if (!ResponseGuard.isUsableResponse(result)) { perHostDelay(); continue; }
     *   // Safe to analyze result.response().bodyToString()
     * </pre>
     */
    public static boolean isUsableResponse(HttpRequestResponse reqResp) {
        if (reqResp == null || reqResp.response() == null) return false;
        boolean usable = isUsableResponse(reqResp.response());
        if (!usable) {
            // Notify throttle controller so auto-throttle can back off
            ThrottleController tc = throttleController;
            if (tc != null) tc.onBlocked();
        }
        return usable;
    }

    /**
     * Returns true if the response is usable for vulnerability analysis.
     */
    public static boolean isUsableResponse(HttpResponse response) {
        if (response == null) return false;
        int status = response.statusCode();
        return !isBlockedStatus(status, response);
    }

    /**
     * Returns true if the response indicates a WAF block or rate limit.
     * This is the inverse of isUsableResponse — useful for explicit "is this blocked?" checks.
     */
    public static boolean isBlocked(HttpRequestResponse reqResp) {
        return !isUsableResponse(reqResp);
    }

    /**
     * Returns true if the response status code indicates rate limiting.
     * Modules doing time-based detection should check this BEFORE measuring elapsed time,
     * because WAF rate-limit delays are indistinguishable from time-based injection delays.
     */
    public static boolean isRateLimited(HttpResponse response) {
        if (response == null) return false;
        return response.statusCode() == RATE_LIMITED;
    }

    /**
     * Returns true if the response status code indicates rate limiting.
     */
    public static boolean isRateLimited(HttpRequestResponse reqResp) {
        if (reqResp == null || reqResp.response() == null) return false;
        return isRateLimited(reqResp.response());
    }

    /**
     * Checks if a time-based measurement is trustworthy.
     * Returns false if the response indicates rate limiting or infrastructure error,
     * which means the elapsed time reflects WAF/proxy delays, not application behaviour.
     *
     * Usage in time-based detection:
     * <pre>
     *   long elapsed = System.currentTimeMillis() - start;
     *   if (!ResponseGuard.isTimingTrustworthy(result)) continue; // WAF delay, not SQLi
     *   if (elapsed > threshold) { ... }
     * </pre>
     */
    public static boolean isTimingTrustworthy(HttpRequestResponse reqResp) {
        if (reqResp == null || reqResp.response() == null) return false;
        int status = reqResp.response().statusCode();
        // Any infrastructure status code means timing data is from WAF/proxy, not the app.
        // Use the same set as isBlockedStatus() to stay in sync.
        if (INFRASTRUCTURE_STATUS_CODES.contains(status)) return false;
        if (status >= CLOUDFLARE_RANGE_START && status <= CLOUDFLARE_RANGE_END) return false;
        return true;
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Internal logic
    // ════════════════════════════════════════════════════════════════════════

    private static boolean isBlockedStatus(int status, HttpResponse response) {
        // Infrastructure status codes — always blocked regardless of body
        if (INFRASTRUCTURE_STATUS_CODES.contains(status)) return true;

        // Cloudflare 520-530 range — always blocked
        if (status >= CLOUDFLARE_RANGE_START && status <= CLOUDFLARE_RANGE_END) return true;

        // Check for WAF/CDN headers that indicate the response is from infrastructure
        boolean hasWafHeaders = false;
        for (var header : response.headers()) {
            String name = header.name().toLowerCase(java.util.Locale.ROOT);
            // cf-ray = Cloudflare, x-sucuri-id = Sucuri, x-iinfo = Imperva/Incapsula
            if (name.equals("cf-ray") || name.equals("x-sucuri-id") || name.equals("x-iinfo")
                    || name.equals("x-cdn") || name.equals("x-akamai-transformed")) {
                hasWafHeaders = true;
                break;
            }
        }

        // 403 from any source: check body for WAF signatures.
        // A legitimate app 403 (authorization denied) won't contain WAF keywords.
        if (status == 403) {
            try {
                String body = response.bodyToString();
                if (body != null) {
                    String sample = body.length() > 4096 ? body.substring(0, 4096) : body;
                    if (WAF_BODY_PATTERN.matcher(sample).find()) {
                        return true;
                    }
                }
            } catch (Exception ignored) {}
        }

        // 200 with WAF headers + challenge page body = Cloudflare JS challenge or CAPTCHA.
        // Only scan body when WAF headers are present — avoids false-filtering legitimate
        // responses that mention Cloudflare in their content (e.g., blog posts about WAFs).
        if (status == 200 && hasWafHeaders) {
            try {
                String body = response.bodyToString();
                if (body != null) {
                    String sample = body.length() > 4096 ? body.substring(0, 4096) : body;
                    if (WAF_BODY_PATTERN.matcher(sample).find()) {
                        return true; // Challenge page, not real application content
                    }
                }
            } catch (Exception ignored) {}
        }

        return false;
    }
}
